
import { Song, Language, Category } from './types';

export const LANGUAGES = Object.values(Language);
export const CATEGORIES = Object.values(Category);

const DATASET = {
  TAMIL: [
    { title: 'Idhazhin Oram', artist: 'Anirudh', movie: '3', color: '#9333EA' },
    { title: 'Oh Penne', artist: 'Anirudh', movie: 'Vanakkam Chennai', color: '#9333EA' },
    { title: 'Enna Solla', artist: 'Anirudh', movie: 'Thangamagan', color: '#9333EA' },
    { title: 'Monica', artist: 'Anirudh', movie: 'Coolie', color: '#9333EA' },
    { title: 'Enakenna Yaarum Illaye', artist: 'Anirudh', movie: 'LIK', color: '#9333EA' },
    { title: 'Neeyum Naanum', artist: 'Anirudh', movie: 'NRD', color: '#9333EA' },
    { title: 'Naan Pizhai', artist: 'Anirudh', movie: 'KRK', color: '#9333EA' },
    { title: 'Kannazhaga', artist: 'Anirudh', movie: '3', color: '#9333EA' },
    { title: 'Osaka Osaka', artist: 'Anirudh', movie: 'Vanakkam Chennai', color: '#9333EA' },
    { title: 'Thangamey', artist: 'Anirudh', movie: 'NRD', color: '#9333EA' },
    { title: 'Kadhalaada', artist: 'Anirudh', movie: 'Vivegam', color: '#9333EA' },
    { title: 'Avalukena', artist: 'Anirudh', movie: 'Independent', color: '#9333EA' },
    { title: 'Velicha Poove', artist: 'Anirudh', movie: 'Ethir Neechal', color: '#9333EA' },
    { title: 'Un Vizhigalil', artist: 'Anirudh', movie: 'Maan Karate', color: '#9333EA' },
    { title: 'Kanave Kanave', artist: 'Anirudh', movie: 'David', color: '#9333EA' },
    { title: 'Po Indru Neeyaga', artist: 'Anirudh', movie: 'VIP', color: '#9333EA' },
    { title: 'Yennai Maatrum Kadhale', artist: 'Anirudh', movie: 'NRD', color: '#9333EA' },
    { title: 'Nee Singam Dhan', artist: 'A.R. Rahman', movie: 'Raayan', color: '#FACC15' },
    { title: 'Aga Naga', artist: 'A.R. Rahman', movie: 'PS-2', color: '#FACC15' },
    { title: 'Munbe Vaa', artist: 'A.R. Rahman', movie: 'Sillunu Oru Kaadhal', color: '#FACC15' },
    { title: 'Uyir Urugudhey', artist: 'A.R. Rahman', movie: 'Cobra', color: '#FACC15' },
    { title: 'Kaalathukkum Nee Venum', artist: 'A.R. Rahman', movie: 'VTK', color: '#FACC15' },
    { title: 'Mallipoo', artist: 'A.R. Rahman', movie: 'VTK', color: '#FACC15' },
    { title: 'Snehidhane', artist: 'A.R. Rahman', movie: 'Alaipayuthey', color: '#FACC15' },
    { title: 'Pachai Nirame', artist: 'A.R. Rahman', movie: 'Alaipayuthey', color: '#FACC15' },
    { title: 'Thalapathy Kacheri', artist: 'Thalapathy Vijay', movie: 'Jana Nayagan', color: '#EF4444' },
    { title: 'Ranjithame', artist: 'Thalapathy Vijay', movie: 'Varisu', color: '#EF4444' },
    { title: 'Kutti Story', artist: 'Thalapathy Vijay', movie: 'Master', color: '#EF4444' },
    { title: 'Vaathi Coming', artist: 'Thalapathy Vijay', movie: 'Master', color: '#EF4444' },
    { title: 'Arabic Kuthu', artist: 'Thalapathy Vijay', movie: 'Beast', color: '#EF4444' },
    { title: 'Naa Ready', artist: 'Thalapathy Vijay', movie: 'Leo', color: '#EF4444' },
    { title: 'Selfie Pulla', artist: 'Thalapathy Vijay', movie: 'Kaththi', color: '#EF4444' },
    { title: 'Aalaporaan Thamizhan', artist: 'Thalapathy Vijay', movie: 'Mersal', color: '#EF4444' },
    { title: 'Verithanam', artist: 'Thalapathy Vijay', movie: 'Bigil', color: '#EF4444' },
    { title: 'Oorum Blood', artist: 'Sai Abhyankkar', movie: 'Dude', color: '#06B6D4' },
    { title: 'Aasa Kooda', artist: 'Sai Abhyankkar', movie: 'Single', color: '#06B6D4' },
    { title: 'Katchi Sera', artist: 'Sai Abhyankkar', movie: 'Single', color: '#06B6D4' },
    { title: 'Singari', artist: 'Sai Abhyankkar', movie: 'Dude', color: '#06B6D4' },
    { title: 'Kannukulla', artist: 'Sai Abhyankkar', movie: 'Dude', color: '#06B6D4' },
    { title: 'Sithira Puthiri', artist: 'Sai Abhyankkar', movie: 'Single', color: '#06B6D4' },
    { title: 'Kanja Poovu Kannala', artist: 'Yuvan Shankar Raja', movie: 'Viruman', color: '#10B981' },
    { title: 'Madura Veeran', artist: 'Yuvan Shankar Raja', movie: 'Viruman', color: '#10B981' },
    { title: 'Oru Naalil', artist: 'Yuvan Shankar Raja', movie: 'Pudhupettai', color: '#10B981' },
    { title: 'Loosu Penne', artist: 'Yuvan Shankar Raja', movie: 'Vallavan', color: '#10B981' },
    { title: 'Kadhal Valarthen', artist: 'Yuvan Shankar Raja', movie: 'Manmadhan', color: '#10B981' },
    { title: 'Oru Manam', artist: 'Harris Jayaraj', movie: 'Dhruva Natchathiram', color: '#3B82F6' },
    { title: 'Mundhinam', artist: 'Harris Jayaraj', movie: 'Vaaranam Aayiram', color: '#3B82F6' },
    { title: 'Vaseegara', artist: 'Harris Jayaraj', movie: 'Minnale', color: '#3B82F6' },
    { title: 'Unnale Unnale', artist: 'Harris Jayaraj', movie: 'Unnale Unnale', color: '#3B82F6' },
    { title: 'Anbe En Anbe', artist: 'Harris Jayaraj', movie: 'Dhaam Dhoom', color: '#3B82F6' },
    { title: 'Kaattu Payale', artist: 'GV Prakash', movie: 'Soorarai Pottru', color: '#F97316' },
    { title: 'Veyyon Silli', artist: 'GV Prakash', movie: 'Soorarai Pottru', color: '#F97316' },
    { title: 'Pookkal Pookkum', artist: 'GV Prakash', movie: 'Madrasapattinam', color: '#F97316' },
    { title: 'Inba Inba', artist: 'GV Prakash', movie: 'Japan', color: '#F97316' },
    { title: 'Yedi', artist: 'GV Prakash', movie: 'NEB', color: '#F97316' },
  ],
  TELUGU: [
    { title: 'New York Nagaram', artist: 'A.R. Rahman', movie: 'Nuvvu Nenu Prema', color: '#1E40AF' },
    { title: 'Vellipomaakey', artist: 'A.R. Rahman', movie: 'Saahasam Swaasaga Saagipo', color: '#1E40AF' },
    { title: 'Cheliya Cheliya', artist: 'A.R. Rahman', movie: 'Kushi', color: '#1E40AF' },
    { title: 'Roja Roja', artist: 'A.R. Rahman', movie: 'Roja', color: '#1E40AF' },
    { title: 'Telephone Dhwani La', artist: 'A.R. Rahman', movie: 'Indian', color: '#1E40AF' },
    { title: 'Poolane Kunukeyamantaa', artist: 'A.R. Rahman', movie: 'I', color: '#1E40AF' },
    { title: 'Ale Ale', artist: 'A.R. Rahman', movie: 'Boys', color: '#1E40AF' },
    { title: 'Fear Song', artist: 'Anirudh', movie: 'Devara', color: '#1E40AF' },
    { title: 'Pataas Pilla', artist: 'Anirudh', movie: 'DJ Tillu', color: '#1E40AF' },
    { title: 'Kalaavathi', artist: 'Anirudh', movie: 'Sarkaru Vaari Paata', color: '#1E40AF' },
    { title: 'Whistle Podu', artist: 'Anirudh', movie: 'GOAT', color: '#1E40AF' },
    { title: 'Malamal', artist: 'Anirudh', movie: 'Leo', color: '#1E40AF' },
    { title: 'Oh My Friend', artist: 'Anirudh', movie: 'Independent', color: '#1E40AF' },
    { title: 'Panchadaara Bomma', artist: 'Keeravani', movie: 'Magadheera', color: '#1E40AF' },
    { title: 'Natu Natu', artist: 'Keeravani', movie: 'RRR', color: '#1E40AF' },
    { title: 'Pedave Palikina', artist: 'Keeravani', movie: 'Nani', color: '#1E40AF' },
    { title: 'Mounamgane Edagamani', artist: 'Keeravani', movie: 'Naani', color: '#1E40AF' },
    { title: 'Nigama Nigamantha', artist: 'Keeravani', movie: 'Annamayya', color: '#1E40AF' },
    { title: 'Swagathaanjali', artist: 'Keeravani', movie: 'Baahubali', color: '#1E40AF' },
    { title: 'Ee Velalo Neevu', artist: 'Keeravani', movie: 'Gulabi', color: '#1E40AF' },
    { title: 'Ramuloo Ramulaa', artist: 'Thaman S', movie: 'Ala Vaikunthapurramuloo', color: '#1E40AF' },
    { title: 'Butta Bomma', artist: 'Thaman S', movie: 'Ala Vaikunthapurramuloo', color: '#1E40AF' },
    { title: 'Pilla Chao', artist: 'Thaman S', movie: 'Business Man', color: '#1E40AF' },
    { title: 'Sada Nannu', artist: 'Thaman S', movie: 'Mahanati', color: '#1E40AF' },
    { title: 'Samajavaragamana', artist: 'Thaman S', movie: 'Ala Vaikunthapurramuloo', color: '#1E40AF' },
    { title: 'Dookudu', artist: 'Thaman S', movie: 'Dookudu', color: '#1E40AF' },
    { title: 'Oo Antava Mawa', artist: 'DSP', movie: 'Pushpa', color: '#1E40AF' },
    { title: 'Ranga Ranga Rangasthalaana', artist: 'DSP', movie: 'Rangasthalam', color: '#1E40AF' },
    { title: 'Ammadu Lets Do Kummudu', artist: 'DSP', movie: 'Khaidi No 150', color: '#1E40AF' },
    { title: 'Nannaku Prematho', artist: 'DSP', movie: 'Nannaku Prematho', color: '#1E40AF' },
  ],
  MALAYALAM: [
    { title: 'Kannaadi Koodum Kootti', artist: 'Vidyasagar', movie: 'Pranayavarnangal', color: '#064E3B' },
    { title: 'Ethrayo Janmamayi', artist: 'Vidyasagar', movie: 'Summer in Bethlehem', color: '#064E3B' },
    { title: 'Karimizhi Kuruviye', artist: 'Vidyasagar', movie: 'Meesa Madhavan', color: '#064E3B' },
    { title: 'Vennila Chandanakinnam', artist: 'Vidyasagar', movie: 'Azhakiya Ravanan', color: '#064E3B' },
    { title: 'Pinneyum Pinneyum', artist: 'Vidyasagar', movie: 'Krishnagudiyil Oru Pranayakalathu', color: '#064E3B' },
    { title: 'Mizhiyariyaathe', artist: 'Vidyasagar', movie: 'Niram', color: '#064E3B' },
    { title: 'Aaro Viral Neetti', artist: 'Vidyasagar', movie: 'Pranayavarnangal', color: '#064E3B' },
    { title: 'Vathikkalu Vellaripravu', artist: 'Jayachandran', movie: 'Sufiyum Sujatayum', color: '#064E3B' },
    { title: 'Kaathirunnu', artist: 'Jayachandran', movie: 'Ennu Ninte Moideen', color: '#064E3B' },
    { title: 'Kannondu Chollanu', artist: 'Jayachandran', movie: 'Ennu Ninte Moideen', color: '#064E3B' },
    { title: 'Ariyathe Ariyathe', artist: 'Jayachandran', movie: 'Raavanaprabhu', color: '#064E3B' },
    { title: 'Ithaloornnu Veena', artist: 'Jayachandran', movie: 'Thanmathra', color: '#064E3B' },
    { title: 'Illuminati', artist: 'Sushin Shyam', movie: 'Aavesham', color: '#064E3B' },
    { title: 'Cherathukal', artist: 'Sushin Shyam', movie: 'Kumbalangi Nights', color: '#064E3B' },
    { title: 'Uyiril Thodum', artist: 'Sushin Shyam', movie: 'Kumbalangi Nights', color: '#064E3B' },
  ],
  KANNADA: [
    { title: 'Salaam Rocky Bhai', artist: 'Ravi Basrur', movie: 'KGF 1', color: '#991B1B' },
    { title: 'Toofan', artist: 'Ravi Basrur', movie: 'KGF 2', color: '#991B1B' },
    { title: 'Ugramm Veeram', artist: 'Ravi Basrur', movie: 'Ugramm', color: '#991B1B' },
    { title: 'Mehabooba', artist: 'Ravi Basrur', movie: 'KGF 2', color: '#991B1B' },
    { title: 'Geleya Nanna Geleya', artist: 'Ravi Basrur', movie: 'Independent', color: '#991B1B' },
    { title: 'Chanda Chanda', artist: 'Ravi Basrur', movie: 'Anjani Putra', color: '#991B1B' },
    { title: 'Bhairathi Ranagal', artist: 'Ravi Basrur', movie: 'Mufti', color: '#991B1B' },
    { title: 'Sulthana', artist: 'Ravi Basrur', movie: 'KGF 2', color: '#991B1B' },
    { title: 'Bombe Helutaithe', artist: 'V. Harikrishna', movie: 'Raajakumara', color: '#991B1B' },
    { title: 'Minchagi Neenu', artist: 'V. Harikrishna', movie: 'Gaalipata', color: '#991B1B' },
    { title: 'Mugulu Nage', artist: 'V. Harikrishna', movie: 'Mugulu Nage', color: '#991B1B' },
    { title: 'Kaarmoda Saridhu', artist: 'V. Harikrishna', movie: 'Mugulu Nage', color: '#991B1B' },
    { title: 'Bangari Yare Nee', artist: 'V. Harikrishna', movie: 'Junglee', color: '#991B1B' },
    { title: 'Summane Summane', artist: 'V. Harikrishna', movie: 'Gaalipata', color: '#991B1B' },
    { title: 'Pushpavati', artist: 'V. Harikrishna', movie: 'Kranti', color: '#991B1B' },
    { title: 'Annthamma', artist: 'V. Harikrishna', movie: 'Mr. and Mrs. Ramachari', color: '#991B1B' },
    { title: 'Belageddu', artist: 'Ajaneesh Loknath', movie: 'Kirik Party', color: '#991B1B' },
    { title: 'Ra Ra Rakkamma', artist: 'Ajaneesh Loknath', movie: 'Vikrant Rona', color: '#991B1B' },
    { title: 'Soul Of Dia', artist: 'Ajaneesh Loknath', movie: 'Dia', color: '#991B1B' },
    { title: 'Gaatiya Ilidu', artist: 'Ajaneesh Loknath', movie: 'Ulidavaru Kandanthe', color: '#991B1B' },
  ],
  HINDI: [
    { title: 'Kesariya', artist: 'Pritam', movie: 'Brahmastra', color: '#1F2937' },
    { title: 'Channa Mereya', artist: 'Pritam', movie: 'ADHM', color: '#1F2937' },
    { title: 'Hawayein', artist: 'Pritam', movie: 'Jab Harry Met Sejal', color: '#1F2937' },
    { title: 'Agar Tum Saath Ho', artist: 'A.R. Rahman', movie: 'Tamasha', color: '#1F2937' },
    { title: 'Kun Faya Kun', artist: 'A.R. Rahman', movie: 'Rockstar', color: '#1F2937' },
    { title: 'Shayad', artist: 'Pritam', movie: 'Love Aaj Kal', color: '#1F2937' },
    { title: 'Enna Sona', artist: 'A.R. Rahman', movie: 'Ok Jaanu', color: '#1F2937' },
    { title: 'Tujhe Kitna Chahne Lage', artist: 'Mithoon', movie: 'Kabir Singh', color: '#1F2937' },
    { title: 'Khairiyat', artist: 'Pritam', movie: 'Chhichhore', color: '#1F2937' },
    { title: 'Apna Bana Le', artist: 'Sachin-Jigar', movie: 'Bhediya', color: '#1F2937' },
    { title: 'Ae Dil Hai Mushkil', artist: 'Pritam', movie: 'ADHM', color: '#1F2937' },
    { title: 'Rait Zara Si', artist: 'A.R. Rahman', movie: 'Atrangi Re', color: '#1F2937' },
    { title: 'Tum Hi Ho', artist: 'Mithoon', movie: 'Aashiqui 2', color: '#1F2937' },
    { title: 'Gerua', artist: 'Pritam', movie: 'Dilwale', color: '#1F2937' },
    { title: 'Agar Ho Tum', artist: 'Jubin Nautiyal', movie: 'Single', color: '#1F2937' },
  ],
  ENGLISH: [
    { title: 'Hotel California', artist: 'Eagles', movie: 'Hotel California', color: '#334155' },
    { title: 'I Will Always Love You', artist: 'Whitney Houston', movie: 'The Bodyguard', color: '#334155' },
    { title: 'Bohemian Rhapsody', artist: 'Queen', movie: 'A Night at the Opera', color: '#334155' },
    { title: 'Shape of You', artist: 'Ed Sheeran', movie: 'Divide', color: '#334155' },
    { title: 'Blinding Lights', artist: 'The Weeknd', movie: 'After Hours', color: '#334155' },
    { title: 'Smells Like Teen Spirit', artist: 'Nirvana', movie: 'Nevermind', color: '#334155' },
    { title: 'Imagine', artist: 'John Lennon', movie: 'Imagine', color: '#334155' },
    { title: 'All of Me', artist: 'John Legend', movie: 'Love in the Future', color: '#334155' },
    { title: 'Blank Space', artist: 'Taylor Swift', movie: '1989', color: '#334155' },
    { title: 'Lovely', artist: 'Billie Eilish', movie: '13 Reasons Why', color: '#334155' },
    { title: 'Hey There Delilah', artist: 'Plain White Ts', movie: 'All That We Needed', color: '#334155' },
    { title: 'Cheap Thrills', artist: 'Sia', movie: 'This Is Acting', color: '#334155' },
    { title: 'Faded', artist: 'Alan Walker', movie: 'Faded', color: '#334155' },
    { title: 'Someone Like You', artist: 'Adele', movie: '21', color: '#334155' },
    { title: 'Dont Stop Believin', artist: 'Journey', movie: 'Escape', color: '#334155' },
  ]
};

const createMockSongs = (): Song[] => {
  const songs: Song[] = [];
  
  const categories = Object.values(Category);

  Object.entries(DATASET).forEach(([langKey, list]) => {
    const language = Language[langKey.charAt(0) + langKey.slice(1).toLowerCase() as keyof typeof Language];
    list.forEach((item, i) => {
      songs.push({
        id: `${langKey.toLowerCase()}-${i}`,
        title: item.title,
        artist: item.artist,
        movie: item.movie,
        album: item.movie,
        themeColor: item.color,
        cover: `https://picsum.photos/seed/lunatone-${langKey}-${i}/400/400`,
        audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
        language: language,
        category: categories[i % categories.length],
        duration: 210 + (i % 60)
      });
    });
  });

  return songs;
};

export const MOCK_SONGS = createMockSongs();
export const BRAND_LOGO = "https://i.ibb.co/LnbM8gT/lunatone-logo.jpg";
